[project]
name = "ars"
version = "6.2.0"
description = "Access Request Service"
dependencies = [
    "ghga-event-schemas~=11.1.1",
    "ghga-service-commons[api,auth]>=7.0,<8",
    "hexkit[mongodb,akafka]>=8.1,<9",
    "httpx>=0.28",
    "typer>=0.21",
]

[project.urls]
Repository = "https://github.com/ghga-de/access-request-service"

[project.scripts]
ars = "ars.__main__:cli"
