[project]
name = "ars"
version = "6.1.1"
description = "Access Request Service"
dependencies = [
    "ghga-event-schemas ~= 10.1.2",
    "ghga-service-commons[api,auth] >= 5.1, <6",
    "hexkit[mongodb,akafka] >= 7.1, <8",
    "httpx >= 0.28",
    "typer >= 0.20",
]

[project.urls]
Repository = "https://github.com/ghga-de/access-request-service"

[project.scripts]
ars = "ars.__main__:cli"
